Remove rq dependency for now (#168)
It's causing this error on publish:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'rq @ git+https://github.com/rq/rq.git@cf501518534429640a9a6d14e022f9329225e701 ; extra == "parallel"'
```

Probably at some point we just want to remove all this Redis stuff. Opened #172 to track that.